import { prisma } from '@/lib/db';

// Helper function to parse group strings (e.g., "4&5" → [4,5], "N1" → [])
function parseGroups(groupStr: string): number[] {
  if (groupStr.startsWith('N')) {
    return [];
  }
  return groupStr.split('&').map(Number).filter(n => !isNaN(n));
}

// Full group data from user's SQL
const groupData = [
  { name: 'Ashok Srinath Prajapati', groups: parseGroups('1') },
  { name: 'Manoj Satyanarayan Vishwakarma', groups: parseGroups('4&5') },
  { name: 'Arun Janu Bhanat', groups: parseGroups('3') },
  { name: 'Sandeep Mansing Mane', groups: parseGroups('2') },
  { name: 'Shashikant Guptanath Maurya', groups: parseGroups('4&6') },
  { name: 'Radheshyam Shivgen Vishwakarma', groups: parseGroups('1') },
  { name: 'Anand Baburao More', groups: parseGroups('8') },
  { name: 'Rajesh Srinath Prajapati', groups: parseGroups('2') },
  { name: 'Sunil Sakharam Deve', groups: parseGroups('4') },
  { name: 'Ramesh Gopal Bhadirke', groups: parseGroups('7') },
  { name: 'Ramesh Dhondu Baikar', groups: parseGroups('5') },
  { name: 'Sitaram Sakharam Deve', groups: parseGroups('7') },
  { name: 'Sandesh Jayram Mandavkar', groups: parseGroups('2') },
  { name: 'Ravindra Mansingh Janala', groups: parseGroups('5') },
  { name: 'Vinod Kumar Ramvilas Gupta', groups: parseGroups('7') },
  { name: 'Kulbahadur Rewansingh Aale', groups: parseGroups('1') },
  { name: 'Sanjay Sahdev Mandvkar', groups: parseGroups('8') },
  { name: 'Sitaram Ganpat Joshi', groups: parseGroups('6') },
  { name: 'Babu Sakharam Jadhav', groups: parseGroups('4') },
  { name: 'Ramasare Surajbali Vishwakarma', groups: parseGroups('3') },
  { name: 'Jayesh Mathurdas Chandarana', groups: parseGroups('6') },
  { name: 'Kishan Narayan Kovoor', groups: parseGroups('8') },
  { name: 'Anil Naresh Patil', groups: parseGroups('3') },
  { name: 'Pankaj Padmakar Arekar', groups: parseGroups('6') },
  { name: 'Sureshchandra Ghurahu Vishwakarma', groups: parseGroups('3') },
  { name: 'Subhash Soma Nawale', groups: parseGroups('3') },
  { name: 'Radheshyam Ramafer Vishwakarma', groups: parseGroups('5') },
  { name: 'Rupesh Namdeo Patil', groups: parseGroups('5') },
  { name: 'Jagdish Ghurahoo Vishwakarma', groups: parseGroups('7') },
  { name: 'Gajanan Namdeo Raut', groups: parseGroups('6') },
  { name: 'Ram Babaji Ghurup', groups: parseGroups('5') },
  { name: 'Vishal Vitthal Gosavi', groups: parseGroups('2') },
  { name: 'Ganpat Sakharam Nawale', groups: parseGroups('6') },
  { name: 'Rakesh Fulchand Sahani', groups: parseGroups('3') },
  { name: 'Munibchand Pannalal Vishwakarma', groups: parseGroups('3') },
  { name: 'Sudhir Yashwant Bargode', groups: parseGroups('4') },
  { name: 'Umesh Pravinbhai Nanda', groups: parseGroups('8') },
  { name: 'Subhash Vishwanath Sahani', groups: parseGroups('1') },
  { name: 'Pyarelal Chhabburam Prajapati', groups: parseGroups('3') },
  { name: 'Amarjeet Rameshwar Gupta', groups: parseGroups('8') },
  { name: 'Shivbachan Ramruchi Prajapati', groups: parseGroups('8') },
  { name: 'Ravindra Chandrakant Jambhale', groups: parseGroups('6') },
  { name: 'Sudama Kumbhakarn Rajbhar', groups: parseGroups('8') },
  { name: 'Subhash Bhagoji Dhanawade', groups: parseGroups('5') },
  { name: 'Prabhudeo Rajendra Gupta', groups: parseGroups('7') },
  { name: 'Ganesh Namdev Patil', groups: parseGroups('6') },
  { name: 'Subhash Pandurang Ghadigaonkar', groups: parseGroups('6') },
  { name: 'Dashrath Shivaji Nikam', groups: parseGroups('1') },
  { name: 'Dilip Shankar Ranjane', groups: parseGroups('5') },
  { name: 'Mukund Laxman Mengde', groups: parseGroups('5') },
  { name: 'Ramkirat Manai Prajapati', groups: parseGroups('7') },
  { name: 'Brijkishor Rampati Kushwaha', groups: parseGroups('8') },
  { name: 'Lalbahadur Vishwakarma', groups: parseGroups('3') },
  { name: 'Santlal Fekuram Chaurasia', groups: parseGroups('7') },
  { name: 'Sitaram Rajaram Rohidas', groups: parseGroups('5') },
  { name: 'Phoolchand Vishwanath Pal', groups: parseGroups('4') },
  { name: 'Anil Shambhu Kotavdekar', groups: parseGroups('2') },
  { name: 'Anil Kumar Kedarnath Prajapati', groups: parseGroups('8') },
  { name: 'Sunil Shambhu Kotawdekar', groups: parseGroups('4') },
  { name: 'Ravindra Mewalal Vishwakarma', groups: parseGroups('8') },
  { name: 'Ghanshyam Sukhai Prajapati', groups: parseGroups('2') },
  { name: 'Rajesh Ramprasad Vishwakarma', groups: parseGroups('7') },
  { name: 'Srikant Shivaji Nikam', groups: parseGroups('1') },
  { name: 'Narendra Janu Bhanat', groups: parseGroups('4') },
  { name: 'Shrikant Guptanath Maurya', groups: parseGroups('5') },
  { name: 'Manoj Naresh Patil', groups: parseGroups('2') },
  { name: 'Deepak Chandrakant Kadu', groups: parseGroups('5') },
  { name: 'Dipak Arjun Shivgan', groups: parseGroups('8') },
  { name: 'Mahesh Laxman More', groups: parseGroups('8') },
  { name: 'Mitesh Harishchandra Mulam', groups: parseGroups('1') },
  { name: 'Manoj Gulabrao Sankapal', groups: parseGroups('4') },
  { name: 'Nitin Gajanan Sayakar', groups: parseGroups('5') },
  { name: 'Mahendra Chandrakant Jamble', groups: parseGroups('2') },
  { name: 'Hardev Sukthi Yadav', groups: parseGroups('4') },
  { name: 'Nilesh Gajanan Saykar', groups: parseGroups('5') },
  { name: 'Rupesh Dipak Gujar', groups: parseGroups('7') },
  { name: 'Mantrilal Pannalal Vishwakarma', groups: parseGroups('7') },
  { name: 'Vivek Indrapal Saroj', groups: parseGroups('2') },
  { name: 'Mangesh Laxman More', groups: parseGroups('6') },
  { name: 'Ajay Dalajeet Vishwakarma', groups: parseGroups('3') },
  { name: 'Arun Kumar Mahendra Vishwakarma', groups: parseGroups('7') },
  { name: 'Mandar Mukund Mengade', groups: parseGroups('8') },
  { name: 'Sandeep Arvind Maurya', groups: parseGroups('2') },
  { name: 'Anil Phoolchand Pal', groups: parseGroups('1') },
  { name: 'Chetan Keshav Kotavdekar', groups: parseGroups('7') },
  { name: 'Shiv Kumar Bansraj Yadav', groups: parseGroups('5') },
  { name: 'Ramchandar Shyamlal Nishad', groups: parseGroups('7') },
  { name: 'Ramavadh Rambachan Yadav', groups: parseGroups('8') },
  { name: 'Parshuram Shivmurat Vishwakarma', groups: parseGroups('8') },
  { name: 'Shailesh Harishchandra Mulam', groups: parseGroups('1') },
  { name: 'Satish Changdev Kudekar', groups: parseGroups('3') },
  { name: 'Satyendrapratap Rampratap Vishwakarma', groups: parseGroups('4') },
  { name: 'Pralahad Arjun Shivgan', groups: parseGroups('7') },
  { name: 'Rishikant Guptnath Maurya', groups: parseGroups('6') },
  { name: 'Dayaram Ramdas Saroj', groups: parseGroups('4') },
  { name: 'Shivsagar Dinanath Yadav', groups: parseGroups('1') },
  { name: 'Avadhraj Parmeshwar Sahani', groups: parseGroups('4') },
  { name: 'Vishwas Keshav Kotavdekar', groups: parseGroups('8') },
  { name: 'Satyaprakash Jogbahadur Kesi', groups: parseGroups('4') },
  { name: 'Kiran Sunil Deve', groups: parseGroups('2') },
  { name: 'Vishwanath Maruti Shigvan', groups: parseGroups('2') },
  { name: 'Anand Kedarnath Prajapati', groups: parseGroups('4') },
  { name: 'Suraj Dattaram Beloshe', groups: parseGroups('8') },
  { name: 'Dhiraj Prakash Triloker', groups: parseGroups('5') },
  { name: 'Mayur Ramesh Lataye', groups: parseGroups('5') },
  { name: 'Rajesh Phoolchand Sahani', groups: parseGroups('3') },
  { name: 'Brahmadev Dayashanker Sahani', groups: parseGroups('4') },
  { name: 'Baijnath Dayashanker Sahani', groups: parseGroups('1') },
  { name: 'Kishor Kumar Raghurai Benbanshi', groups: parseGroups('7') },
  { name: 'Satyanarayan Bekelal Prajapati', groups: parseGroups('3') },
  { name: 'Ramgopal Maataprasad Chauhan', groups: parseGroups('7') },
  { name: 'Shivshankar Ramasare Vishwakarma', groups: parseGroups('8') },
  { name: 'Kaushal Sandesh Mandavkar', groups: parseGroups('6') },
  { name: 'Makardhwaj Shriramnarayan Thakur', groups: parseGroups('7') },
  { name: 'Sumit Kumar Kishor Benbanshi', groups: parseGroups('7') },
  { name: 'Ravindra Ratnaker Kocharekar', groups: parseGroups('6') },
  { name: 'Vinayak Ramesh Latye', groups: parseGroups('1') },
  { name: 'Manish Rajesh Prajapati', groups: parseGroups('2') },
  { name: 'Prashant Dilip Bhojane', groups: parseGroups('4') },
  { name: 'Vikas Munibchand Vishwakarma', groups: parseGroups('7') },
  { name: 'Aadesh Tukaram Kamble', groups: parseGroups('1') },
  { name: 'Sakharam Tukaram Devare', groups: parseGroups('5') },
  { name: 'Shubham Rajkishor Vishwakarma', groups: parseGroups('1') },
  { name: 'Kshitij Rajesh Vishwakarma', groups: parseGroups('7') },
  { name: 'Vishnu Firatoo Rajbhar', groups: parseGroups('4') },
  { name: 'Shubham Shivaji Patil', groups: parseGroups('5') },
  { name: 'Dipesh Dilip Bhojane', groups: parseGroups('3') },
  { name: 'Rajan Firatu Rajbhar', groups: parseGroups('1') },
  { name: 'Vivek Mukund Deve', groups: parseGroups('5') },
  { name: 'Roshan Sitaram Joshi', groups: parseGroups('2') },
  { name: 'Sumeet Shivkumar Yadav', groups: parseGroups('6') },
  { name: 'Anurag Arvind Singh', groups: parseGroups('6') },
  { name: 'Suvitkumar Sureshchandra Vishwakarma', groups: parseGroups('3') },
  { name: 'Sujal Vithal Shelar', groups: parseGroups('6') },
  { name: 'Roshan Ramchandra Jadhav', groups: parseGroups('6') },
  { name: 'Sundaram Rajesh Vishwakarma', groups: parseGroups('6') },
  { name: 'Amar Hari Mahadik', groups: parseGroups('6') },
  { name: 'Prashant Bhimrao Patil', groups: parseGroups('6') },
  { name: 'Praveen Kumar Ramnihore Pal', groups: parseGroups('4') },
  { name: 'Aakash Tukaram Kamble', groups: parseGroups('1') },
  { name: 'Harsh Bhavesh Shirke', groups: parseGroups('1') },
  { name: 'Pratham Ravindra Janala', groups: parseGroups('5') },
  { name: 'Suyash Anand More', groups: parseGroups('1') },
  { name: 'Surendra Subhash Sahani', groups: parseGroups('2') },
  { name: 'Pratham Rajkishor Vishwakarma', groups: parseGroups('3') },
  { name: 'Mukesh Subhash Dhanawade', groups: parseGroups('3') },
  { name: 'Manmohan Radheshyam Vishwakarma', groups: parseGroups('3') },
  { name: 'Vinay Ravindra Janala', groups: parseGroups('8') },
  { name: 'Mandhir Radheshyam Vishwakarma', groups: parseGroups('3') },
  { name: 'Aditya Ghanshyam Prajapati', groups: parseGroups('3') },
  { name: 'Deepak Chhedi Jaiswar', groups: parseGroups('7') },
  { name: 'Hardik Shivadhaar Yadav', groups: parseGroups('6') },
  { name: 'Vinit Ramsakal Prajapati', groups: parseGroups('2') },
  { name: 'Jitesh Rajesh Ram', groups: parseGroups('2') },
  { name: 'Sanskar Sagar Patil', groups: parseGroups('6') },
  { name: 'Prem Avadhraj Sahani', groups: parseGroups('1') },
  { name: 'Gyaanchand Motilal Vishwakarma', groups: parseGroups('1') },
  { name: 'Arvind Ramraj Maurya', groups: parseGroups('4') },
  { name: 'Kiran Dattaram Beloshe', groups: parseGroups('5') },
  { name: 'Syambali Ramlakhan Vishwakarma', groups: parseGroups('2') },
  { name: 'Harsh Manoj Sankpal', groups: parseGroups('4') },
  { name: 'Dashrath Bhikhu Dhangat', groups: parseGroups('6') },
  { name: 'Suchitra Sandesh Mandavkar', groups: parseGroups('1') },
  { name: 'Jyoti Kishor Wagh', groups: parseGroups('2') },
  { name: 'Ujjwala Maruti Shigvan', groups: parseGroups('6') },
  { name: 'Minakshi Kishor Bandagale', groups: parseGroups('4') },
  { name: 'Sonali Subhash Dhanawade', groups: parseGroups('5') },
  { name: 'Geeta Premanand Jadhav', groups: parseGroups('5') },
  { name: 'Vaishali Madhukar Gudekar', groups: parseGroups('5') },
  { name: 'Vandana Anil Patil', groups: parseGroups('3') },
  { name: 'Manisha Rupesh Patil', groups: parseGroups('6') },
  { name: 'Archana Umesh Maurya', groups: parseGroups('5') },
  { name: 'Sunita Arun Bhanat', groups: parseGroups('3') },
  { name: 'Jyoti Subhash Batawale', groups: parseGroups('5') },
  { name: 'Ranjana Ganpat Nawale', groups: parseGroups('5') },
  { name: 'Bharati Ramesh Late', groups: parseGroups('3') },
  { name: 'Shaila Prakash Tandelkar', groups: parseGroups('5') },
  { name: 'Jyoti Nilesh Vishwakarma', groups: parseGroups('3') },
  { name: 'Nandini Maruti Shigvan', groups: parseGroups('6') },
  { name: 'Dipali Sandeep Kadam', groups: parseGroups('2') },
  { name: 'Nilam Premchand Gupta', groups: parseGroups('2') },
  { name: 'Sushila Raju Vishwakarma', groups: parseGroups('3') },
  { name: 'Suvarna Gajanan Raut', groups: parseGroups('8') },
  { name: 'Sujata Sitaram Deve', groups: parseGroups('7') },
  { name: 'Dipti Dipak Kadu', groups: parseGroups('5') },
  { name: 'Sanjana Prakash Gaikwad', groups: parseGroups('1') },
  { name: 'Sonal Sunil Deve', groups: parseGroups('6') },
  { name: 'Punam Mitesh Mulam', groups: parseGroups('7') },
  { name: 'Surekha Sakharam Dhangat', groups: parseGroups('5') },
  { name: 'Shraddha Shashikant Maurya', groups: parseGroups('6') },
  { name: 'Pavitra Jogbahadur Kesi', groups: parseGroups('2') },
  { name: 'Rasika Dilip Ranjane', groups: parseGroups('5') },
  { name: 'Madhavi Mahadev Jambhale', groups: parseGroups('5') },
  { name: 'Sushma Ajit Parave', groups: parseGroups('5') },
  { name: 'Sarita Rajesh Sahani', groups: parseGroups('1') },
  { name: 'Madhu lata Munibchand Vishwakarma', groups: parseGroups('1') },
  { name: 'Pramila Virendra Vishwakarma', groups: parseGroups('2') },
  { name: 'Geeta Ravindra Janala', groups: parseGroups('6') },
  { name: 'Vandana Maruti Shigvan', groups: parseGroups('6') },
  { name: 'Suganti Ram Kailash Shah', groups: parseGroups('7') },
  { name: 'Vidanti Ram Kailash Shah', groups: parseGroups('7') },
  { name: 'Usha Ramayan Vishwakarma', groups: parseGroups('7') },
  { name: 'Kalavati Ashok Prajapati', groups: parseGroups('7') },
  { name: 'Barkha Daljeet Vishwakarma', groups: parseGroups('3') },
  { name: 'Mamta Sanjay Upadhyay', groups: parseGroups('6') },
  { name: 'Swati Sitaram Joshi', groups: parseGroups('8') },
  { name: 'Sneha Sitaram Joshi', groups: parseGroups('6') },
  { name: 'Snehal Sunil Deve', groups: parseGroups('6') },
  { name: 'Priyanka Raghu Nath Salvi', groups: parseGroups('8') },
  { name: 'Manali Mukund Deve', groups: parseGroups('6') },
  { name: 'Shweta Sitaram Kudkar', groups: parseGroups('2') },
  { name: 'Deepika Dilip Bhojane', groups: parseGroups('2') },
  { name: 'Urmila Subhash Sahani', groups: parseGroups('2') },
  { name: 'Geeta Rajkishor Vishwakarma', groups: parseGroups('8') },
  { name: 'Manda Krushna Patil', groups: parseGroups('1') },
  { name: 'Bandini Vilas Balkate', groups: parseGroups('4') },
  { name: 'Reena Dashrath Nikam', groups: parseGroups('4') },
  { name: 'Aakansha Subhash Dhanawade', groups: parseGroups('8') },
  { name: 'Anita Kishor Benbanshi', groups: parseGroups('2') },
  { name: 'Sunita Subhash Sahani', groups: parseGroups('2') },
  { name: 'Roshni Eknath Tambe', groups: parseGroups('8') },
  { name: 'Shalini Sureshchandra Vishwakarma', groups: parseGroups('5') },
  { name: 'Sushmita Shyambihari Morya', groups: parseGroups('4') },
  { name: 'Pooja Santosh Vishwakarma', groups: parseGroups('4') },
  { name: 'Sarita Rajesh Prajapati', groups: parseGroups('8') },
  { name: 'Anjali Indrapal Bagdi', groups: parseGroups('5') },
  { name: 'Pooja Subhash Sahani', groups: parseGroups('4') },
  { name: 'Sonam Rajkishor Vishwakarma', groups: parseGroups('7') },
  { name: 'Esha Umesh Maurya', groups: parseGroups('7') },
  { name: 'Kajal Shivaji Patil', groups: parseGroups('8') },
  { name: 'Pavitra Kulbahadur Ale', groups: parseGroups('8') },
  { name: 'Suchita Sureshchandra Vishwakarma', groups: parseGroups('3') },
  { name: 'Simran Sandesh Mandavkar', groups: parseGroups('8') },
  { name: 'Milan Dilip Bhojane', groups: parseGroups('4') },
  { name: 'Asha Baburao Jadhav', groups: parseGroups('4') },
  { name: 'Jayashree Shantaram Raynak', groups: parseGroups('7') },
  { name: 'Malati Radhyeshyam Vishwakarma', groups: parseGroups('4') },
  { name: 'Anuradha Mukund Mengade', groups: parseGroups('5') },
  { name: 'Nalini Raghunath Salavi', groups: parseGroups('3') },
  { name: 'Rasika Ratnaker Kocharekar', groups: parseGroups('4') },
  { name: 'Kishori Munibchand Vishwakarma', groups: parseGroups('1') },
  { name: 'Pramila Satyanarayan Prajapati', groups: parseGroups('2') },
  { name: 'Shakuntala Anand More', groups: parseGroups('2') },
  { name: 'Subhangi Keshav Kotavdekar', groups: parseGroups('4') },
  { name: 'Sapna Sunil Deve', groups: parseGroups('6') },
  { name: 'Miradevi Shriramnarayan Thakur', groups: parseGroups('3') },
  { name: 'Pratibha Prakash Tirlotkar', groups: parseGroups('3') },
  { name: 'Geeta Kishor Benbanshi', groups: parseGroups('2') },
  { name: 'Minal Mukund Deve', groups: parseGroups('6') },
  { name: 'Pranali Sitaram Joshi', groups: parseGroups('6') },
  { name: 'Namita Sakharam Devare', groups: parseGroups('8') },
  { name: 'Ishika Arun Bhanat', groups: parseGroups('3') },
  { name: 'Jyoti Satyanarayan Prajapati', groups: parseGroups('4') },
  { name: 'Premlata Mantrilal Vishwakarma', groups: parseGroups('1') },
  { name: 'Sujata Santosh Patil', groups: parseGroups('1') },
  { name: 'Supriya Dipak Shivgan', groups: parseGroups('1') },
  { name: 'Ranju Rishikant Maurya', groups: parseGroups('6') },
  { name: 'Manju Devi (Shashilata) Shivsagar Yadav', groups: parseGroups('4') },
  { name: 'Chhaya Gavade (Sakshi Santosh Pawar)', groups: parseGroups('1') },
  { name: 'Shalini Shyambihari Maurya', groups: parseGroups('8') },
  { name: 'Roshni Pramod Vishwakarma', groups: parseGroups('1') },
  { name: 'Anchal Amarjeet Gupta', groups: parseGroups('8') },
  { name: 'Taruna Rajesh Bhatt', groups: parseGroups('7') },
  { name: 'Urmila Rammilan Prajapati', groups: parseGroups('3') },
  { name: 'Vibha Kamlesh Vishwakarma', groups: parseGroups('4') },
  { name: 'Utkarsh Santosh Pawar', groups: parseGroups('4') },
  { name: 'Priya Vitthal Tungatkar', groups: parseGroups('2') },
  { name: 'Ankita Shastrilal Vishwakarma', groups: parseGroups('7') },
  { name: 'Sujata Subhash Ghadigaonkar', groups: parseGroups('3') },
  { name: 'Sujata Siddhesh Patil', groups: parseGroups('1') },
  { name: 'Sakshi Santosh Pawar', groups: parseGroups('1') },
  { name: 'Shashilata Shivsagar Yadav', groups: parseGroups('1') },
  { name: 'Shivkumari Hardev Yadav', groups: parseGroups('1') },
  { name: 'Pramila Tribuvan Kashyap', groups: parseGroups('3') },
  { name: 'Asha Shivkumar Yadav', groups: parseGroups('5') },
  { name: 'Anita Rajesh Bhatt', groups: parseGroups('7') },
  { name: 'Sarita Baliram Pawar', groups: parseGroups('8') },
  { name: 'Rekha Samsher Janala', groups: parseGroups('6') },
  { name: 'Sonali Rajesh Vishwakarma', groups: parseGroups('4') },
  { name: 'Vrunmaye Sanjay Shinde', groups: parseGroups('5') },
  { name: 'Anita Shrikant Maurya', groups: parseGroups('6') },
  { name: 'Abhay Shrikant Maurya', groups: parseGroups('N1') },
  { name: 'Prajwal Sagar Patil', groups: parseGroups('N2') },
  { name: 'Hardik Shivkumar Yadav', groups: parseGroups('N3') },
  { name: 'Satyam Sushil Yadav', groups: parseGroups('N4') },
  { name: 'Vedant Kishor Nikam', groups: parseGroups('N5') },
  { name: 'Tejas Rajendra Dalvi', groups: parseGroups('N6') },
  { name: 'Lucky Ramaasare Prajapati', groups: parseGroups('N7') },
  { name: 'Lakshya Anil Kotavdekar', groups: parseGroups('N8') },
  { name: 'Shivam Arvind Sharma', groups: parseGroups('N9') },
  { name: 'Mohit Rambrij Chauhan', groups: parseGroups('N10') },
  { name: 'Bhaskar Bramhadev Sahani', groups: parseGroups('N11') },
  { name: 'Nayan Rakesh Sahani', groups: parseGroups('N12') },
  { name: 'Aayush Sanjay Maurya', groups: parseGroups('N13') },
  { name: 'Sandesh Ramjiyavan Verma', groups: parseGroups('N14') },
  { name: 'Aayush Sandeep Kadam', groups: parseGroups('N15') },
  { name: 'Aaradhy Vaishali Tambe', groups: parseGroups('N16') },
  { name: 'Aayush Ramavadh Yadav', groups: parseGroups('N17') },
  { name: 'Sandeep Sanjay Shinde', groups: parseGroups('N18') },
  { name: 'Naman Anand Verma', groups: parseGroups('N19') },
  { name: 'Shukran Manoj Vishwakarma', groups: parseGroups('N20') },
  { name: 'Alisha Shrikant Maurya', groups: parseGroups('N1') },
  { name: 'Tanishka Vijay Bhosale', groups: parseGroups('N2') },
  { name: 'Sharayu Sandesh Namugade', groups: parseGroups('N3') },
  { name: 'Shravani Vithal Shelar', groups: parseGroups('N4') },
  { name: 'Simran Vijay Dakwa', groups: parseGroups('N5') },
  { name: 'Sunakshi Pradeep Vishwakarma', groups: parseGroups('N6') },
  { name: 'Ishwari Mahadev Jadhav', groups: parseGroups('N7') },
  { name: 'Aditi Anil Gupta', groups: parseGroups('N8') },
  { name: 'Mayuri Mahadev Jadhav', groups: parseGroups('N9') },
  { name: 'Akshta Datta Kurne', groups: parseGroups('N10') },
  { name: 'Anita Datta Kurne', groups: parseGroups('N11') },
  { name: 'Shalini Mansingh Patel', groups: parseGroups('N12') },
];

async function main() {
  console.log('Starting to apply group data...');
  const results: { name: string; status: string }[] = [];
  
  for (const data of groupData) {
    // Try both exact match and with " ji" suffix
    const user = await prisma.user.findFirst({
      where: {
        OR: [
          { name: { equals: data.name, mode: 'insensitive' } },
          { name: { equals: `${data.name} ji`, mode: 'insensitive' } },
        ],
      },
    });
    
    if (user) {
      await prisma.user.update({
        where: { id: user.id },
        data: { groups: data.groups },
      });
      results.push({ name: data.name, status: 'Updated' });
      console.log(`Updated: ${data.name} → ${data.groups}`);
    } else {
      results.push({ name: data.name, status: 'Not found' });
      console.log(`Not found: ${data.name}`);
    }
  }
  
  console.log('Group data applied successfully!');
  console.log('Results:', results);
}

main()
  .catch((e) => {
    console.error('Error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
