"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "en" | "hi" | "mr";

type LanguageContextType = {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
};

const translations: Record<Language, Record<string, string>> = {
  en: {
    dashboard: "Dashboard",
    attendance: "Attendance",
    reports: "Reports",
    members: "Members",
    profile: "Profile",
    logout: "Logout",
    apply_filter: "Apply Filter",
    reset: "Reset",
    group: "Group",
    status: "Status",
    member: "Member",
    from_date: "From Date",
    to_date: "To Date",
    all_status: "All Status",
    all_members: "All Members",
    all_groups: "All Groups",
    present: "Present",
    pv_vardi: "PV (Vardi)",
    absent: "Absent",
    loading: "Loading...",
    no_records: "No records for this filter",
    pending: "Pending",
    approved: "Approved",
    all: "All",
    welcome: "Welcome back",
    admin_panel: "Admin Panel",
    member_portal: "Member Portal",
    mark_attendance: "Mark Attendance",
    my_records: "My Records",
    activity: "Activity",
    change_password: "Change Password",
    settings: "Settings",
    group_duty: "Group {group} Duty",
    quick_actions: "Quick Actions",
    attendance_pv_only: "Attendance % (PV only)",
    present_p: "Present (P)",
    absent_a: "Absent",
    my_duty_this_month: "My duty this month",
    fixed_pattern: "{month} — fixed pattern, actual dates below",
    no_sewa_assigned: "No sewa assigned",
    admin_will_set: "Admin will set First, Second, Third, or Extra sewa for you.",
    this_months_attendance: "This month's attendance",
    not_counted_in_percent: "Not counted in %",
    pv_counts_toward: "4 PV = 100% · counts toward %",
    sewa_pattern_set: "Sewa pattern set — dates for this month could not be calculated.",
    sign_out: "Sign out",
    no_approved_records: "No approved records this month",
    mark_attendance_at_centre: "Mark attendance at an approved centre.",
    // Page Titles
    admin_dashboard: "Admin Dashboard",
    broadcast_notice: "Broadcast Notice",
    members_management: "Members",
    attendance_management: "Attendance",
    reports_dashboard: "Reports",
    settings_page: "Settings",
    my_profile_page: "My Profile",
    recent_attendance: "Recent Attendance",
    total_members: "Total Members",
    present_today: "Present Today",
    pv_today: "PV Today",
    absent_today: "Absent Today",
    pv_pending: "PV Pending",
    needs_approval: "Needs Approval",
    // Common UI
    send: "Send",
    save: "Save",
    saving: "Saving...",
    delete: "Delete",
    cancel: "Cancel",
    confirm: "Confirm",
    edit: "Edit",
    create: "Create",
    search: "Search",
    filter: "Filter",
    export: "Export",
    download: "Download",
    print: "Print",
    share: "Share",
    close: "Close",
    back: "Back",
    next: "Next",
    previous: "Previous",
    submit: "Submit",
    apply: "Apply",
    clear: "Clear",
    refresh: "Refresh",
    view: "View",
    manage: "Manage",
    configure: "Configure",
    customize: "Customize",
    // Notifications
    success: "Success",
    error: "Error",
    warning: "Warning",
    info: "Information",
    notification: "Notification",
    alert: "Alert",
    confirmation: "Confirmation",
    // Status
    active: "Active",
    inactive: "Inactive",
    completed: "Completed",
    in_progress: "In Progress",
    scheduled: "Scheduled",
    overdue: "Overdue",
    cancelled: "Cancelled",
    rejected: "Rejected",
    // Time
    today: "Today",
    yesterday: "Yesterday",
    tomorrow: "Tomorrow",
    this_week: "This Week",
    last_week: "Last Week",
    this_month: "This Month",
    last_month: "Last Month",
    this_year: "This Year",
    last_year: "Last Year",
    date: "Date",
    time: "Time",
    day: "Day",
    week: "Week",
    month: "Month",
    year: "Year",
    hour: "Hour",
    minute: "Minute",
    second: "Second",
    // User
    username: "Username",
    email: "Email",
    phone: "Phone",
    mobile: "Mobile",
    password: "Password",
    confirm_password: "Confirm Password",
    current_password: "Current Password",
    new_password: "New Password",
    full_name: "Full Name",
    first_name: "First Name",
    last_name: "Last Name",
    display_name: "Display Name",
    bio: "Bio",
    about: "About",
    avatar: "Avatar",
    profile_picture: "Profile Picture",
    // Role
    role: "Role",
    admin: "Admin",
    superadmin: "Super Admin",
    manager: "Manager",
    supervisor: "Supervisor",
    staff: "Staff",
    employee: "Employee",
    user: "User",
    guest: "Guest",
    visitor: "Visitor",
    // Attendance
    late: "Late",
    on_leave: "On Leave",
    half_day: "Half Day",
    work_from_home: "Work From Home",
    check_in: "Check In",
    check_out: "Check Out",
    shift: "Shift",
    schedule: "Schedule",
    roster: "Roster",
    timesheet: "Timesheet",
    overtime: "Overtime",
    regularization: "Regularization",
    correction: "Correction",
    // Reports
    report: "Report",
    summary: "Summary",
    detailed: "Detailed",
    chart: "Chart",
    graph: "Graph",
    statistics: "Statistics",
    analytics: "Analytics",
    insights: "Insights",
    trends: "Trends",
    comparison: "Comparison",
    breakdown: "Breakdown",
    // Export
    excel: "Excel",
    pdf: "PDF",
    csv: "CSV",
    word: "Word",
    json: "JSON",
    xml: "XML",
    html: "HTML",
    text: "Text",
    // Actions
    add: "Add",
    update: "Update",
    remove: "Remove",
    disable: "Disable",
    enable: "Enable",
    activate: "Activate",
    deactivate: "Deactivate",
    archive: "Archive",
    restore: "Restore",
    merge: "Merge",
    split: "Split",
    move: "Move",
    copy: "Copy",
    paste: "Paste",
    duplicate: "Duplicate",
    import: "Import",
    upload: "Upload",
    sync: "Sync",
    publish: "Publish",
    unpublish: "Unpublish",
    draft: "Draft",
    // Messages
    are_you_sure: "Are you sure?",
    confirm_action: "Please confirm this action",
    changes_saved: "Changes saved successfully",
    changes_not_saved: "Changes could not be saved",
    data_loaded: "Data loaded successfully",
    data_not_loaded: "Data could not be loaded",
    item_created: "Item created successfully",
    item_not_created: "Item could not be created",
    item_updated: "Item updated successfully",
    item_not_updated: "Item could not be updated",
    item_deleted: "Item deleted successfully",
    item_not_deleted: "Item could not be deleted",
    nothing_to_display: "Nothing to display",
    no_results_found: "No results found",
    please_wait: "Please wait...",
    processing: "Processing...",
    loading_data: "Loading data...",
    saving_changes: "Saving changes...",
    deleting_item: "Deleting item...",
    updating_data: "Updating data...",
    creating_item: "Creating item...",
    uploading_file: "Uploading file...",
    downloading_file: "Downloading file...",
    generating_report: "Generating report...",
    sending_email: "Sending email...",
    syncing_data: "Syncing data...",
    please_try_again: "Please try again",
    try_again_later: "Please try again later",
    contact_support: "Please contact support",
    more_info: "More information",
    learn_more: "Learn more",
    read_more: "Read more",
    show_less: "Show less",
    show_more: "Show more",
    expand: "Expand",
    collapse: "Collapse",
    open: "Open",
    back_to_top: "Back to top",
    scroll_to_top: "Scroll to top",
    // Errors
    error_occurred: "An error occurred",
    something_went_wrong: "Something went wrong",
    page_not_found: "Page not found",
    access_denied: "Access denied",
    permission_denied: "Permission denied",
    session_expired: "Session expired",
    timeout_error: "Request timeout",
    network_error: "Network error",
    server_error: "Server error",
    client_error: "Client error",
    validation_error: "Validation error",
    authentication_error: "Authentication error",
    authorization_error: "Authorization error",
    not_found_error: "Not found error",
    conflict_error: "Conflict error",
    rate_limit_error: "Rate limit error",
    service_unavailable: "Service unavailable",
    bad_request: "Bad request",
    unauthorized: "Unauthorized",
    forbidden: "Forbidden",
    not_found: "Not found",
    method_not_allowed: "Method not allowed",
    not_acceptable: "Not acceptable",
    proxy_auth_required: "Proxy authentication required",
    request_timeout: "Request timeout",
    conflict: "Conflict",
    gone: "Gone",
    length_required: "Length required",
    precondition_failed: "Precondition failed",
    payload_too_large: "Payload too large",
    uri_too_long: "URI too long",
    unsupported_media_type: "Unsupported media type",
    range_not_satisfiable: "Range not satisfiable",
    expectation_failed: "Expectation failed",
    teapot: "I'm a teapot",
    misdirected_request: "Misdirected request",
    unprocessable_entity: "Unprocessable entity",
    locked: "Locked",
    failed_dependency: "Failed dependency",
    too_early: "Too early",
    upgrade_required: "Upgrade required",
    precondition_required: "Precondition required",
    too_many_requests: "Too many requests",
    request_header_fields_too_large: "Request header fields too large",
    unavailable_for_legal_reasons: "Unavailable for legal reasons",
    internal_server_error: "Internal server error",
    not_implemented: "Not implemented",
    bad_gateway: "Bad gateway",
    service_unavailable_error: "Service unavailable",
    gateway_timeout: "Gateway timeout",
    http_version_not_supported: "HTTP version not supported",
    variant_also_negotiates: "Variant also negotiates",
    insufficient_storage: "Insufficient storage",
    loop_detected: "Loop detected",
    not_extended: "Not extended",
    network_authentication_required: "Network authentication required",
    network_connect_timeout: "Network connect timeout",
    // Additional UI
    copy_to_clipboard: "Copy to clipboard",
    copied: "Copied",
    share_via: "Share via",
    send_email: "Send email",
    call: "Call",
    message: "Message",
    visit_website: "Visit website",
    open_map: "Open map",
    get_directions: "Get directions",
    // New features
    dark_mode: "Dark Mode",
    light_mode: "Light Mode",
    system_default: "System Default",
    appearance: "Appearance",
    theme: "Theme",
    language: "Language",
    select_language: "Select Language",
    english: "English",
    hindi: "हिन्दी",
    marathi: "मराठी",
    overview: "Overview",
    performance: "Performance",
    distribution: "Distribution",
    details: "Details",
    view_details: "View Details",
    view_all: "View All",
    see_more: "See More",
    load_more: "Load More",
    show_all: "Show All",
    hide: "Hide",
    visible: "Visible",
    hidden: "Hidden",
    enabled: "Enabled",
    disabled: "Disabled",
    pinned: "Pinned",
    unpinned: "Unpinned",
    starred: "Starred",
    unstarred: "Unstarred",
    bookmarked: "Bookmarked",
    favorited: "Favorited",
    subscribed: "Subscribed",
    unsubscribed: "Unsubscribed",
    followed: "Followed",
    unfollowed: "Unfollowed",
    connected: "Connected",
    disconnected: "Disconnected",
    online: "Online",
    offline: "Offline",
    away: "Away",
    busy: "Busy",
    available: "Available",
    unavailable: "Unavailable",
    idle: "Idle",
    finished: "Finished",
    done: "Done",
    failed: "Failed",
    aborted: "Aborted",
    verified: "Verified",
    validated: "Validated",
    confirmed: "Confirmed",
    acknowledged: "Acknowledged",
    recognized: "Recognized",
    identified: "Identified",
    authenticated: "Authenticated",
    authorized: "Authorized",
    permitted: "Permitted",
    allowed: "Allowed",
    accepted: "Accepted",
    invited: "Invited",
    registered: "Registered",
    enrolled: "Enrolled",
    joined: "Joined",
    participated: "Participated",
    attended: "Attended",
    visited: "Visited",
    viewed: "Viewed",
    seen: "Seen",
    received: "Received",
    collected: "Collected",
    gathered: "Gathered",
    accumulated: "Accumulated",
    stored: "Stored",
    preserved: "Preserved",
    backed_up: "Backed Up",
    archived: "Archived",
    recorded: "Recorded",
    logged: "Logged",
    tracked: "Tracked",
    monitored: "Monitored",
    observed: "Observed",
    watched: "Watched",
    inspected: "Inspected",
    examined: "Examined",
    checked: "Checked",
    tested: "Tested",
    // Broadcast
    notice_title: "Notice Title",
    notice_message: "Message",
    notice_type: "Notice Type",
    send_notice: "Send Notice",
    recent_notices: "Recent Notices",
    no_notices: "No notices yet",
    delete_notice: "Delete Notice",
    delete_notice_confirm: "Are you sure you want to delete this notice?",
    // Analytics
    attendance_analytics: "Attendance Analytics",
    performance_metrics: "Performance Metrics",
    attendance_trend: "Attendance Trend",
    monthly_report: "Monthly Report",
    yearly_report: "Yearly Report",
    custom_report: "Custom Report",
    generate_report: "Generate Report",
    export_data: "Export Data",
    // Members
    add_member: "Add Member",
    edit_member: "Edit Member",
    delete_member: "Delete Member",
    member_details: "Member Details",
    member_list: "Member List",
    group_number: "Group Number",
    sewa_duty: "Sewa Duty",
    attendance_history: "Attendance History",
    contact_info: "Contact Information",
    personal_info: "Personal Information",
    // Attendance
    mark_present: "Mark Present",
    mark_absent: "Mark Absent",
    mark_pv: "Mark PV",
    attendance_status: "Attendance Status",
    approval_status: "Approval Status",
    approve_attendance: "Approve Attendance",
    reject_attendance: "Reject Attendance",
    pending_approval: "Pending Approval",
    approved_attendance: "Approved Attendance",
    rejected_attendance: "Rejected Attendance",
    // Profile
    update_profile: "Update Profile",
    change_photo: "Change Photo",
    upload_photo: "Upload Photo",
    remove_photo: "Remove Photo",
    photo_uploaded: "Photo uploaded successfully",
    photo_removed: "Photo removed successfully",
    profile_updated: "Profile updated successfully",
    // Settings
    general_settings: "General Settings",
    notification_settings: "Notification Settings",
    security_settings: "Security Settings",
    language_settings: "Language Settings",
    theme_settings: "Theme Settings",
    system_theme: "System Theme",
    // Quick Actions
    quick_mark: "Quick Mark",
    bulk_action: "Bulk Action",
    import_export: "Import/Export",
    generate_pdf: "Generate PDF",
    print_report: "Print Report",
    // Empty States
    no_data: "No data available",
    no_results: "No results found",
    no_records_found: "No records found",
    no_members_found: "No members found",
    no_attendance_records: "No attendance records",
    no_notices_found: "No notices found",
    // Loading
    processing_request: "Processing request...",
    // Success Messages
    action_completed: "Action completed successfully",
    // Error Messages
    action_failed: "Action failed",
    // Confirmation Messages
    confirm_delete: "Are you sure you want to delete this item?",
    unsaved_changes: "You have unsaved changes. Do you want to leave?",
    // Validation Messages
    required_field: "This field is required",
    invalid_email: "Please enter a valid email address",
    invalid_phone: "Please enter a valid phone number",
    password_mismatch: "Passwords do not match",
    min_length: "Must be at least {min} characters",
    max_length: "Must be at most {max} characters",
    // Accessibility
    skip_to_content: "Skip to main content",
    main_navigation: "Main navigation",
    breadcrumb: "Breadcrumb",
    search_site: "Search this site",
    close_menu: "Close menu",
    open_menu: "Open menu",
    toggle_sidebar: "Toggle sidebar",
    // Meta
    app_name: "Sewadal Attendance",
    app_description: "Attendance Management System for Sewadal",
    version: "Version",
    copyright: "© {year} Sewadal. All rights reserved.",
    powered_by: "Powered by",
    // Greetings
    good_morning: "Good Morning",
    good_afternoon: "Good Afternoon",
    good_evening: "Good Evening",
    good_night: "Good Night",
    welcome_back: "Welcome back",
    hello: "Hello",
    hi: "Hi",
    dear: "Dear",
  },
  hi: {
    dashboard: "डैशबोर्ड",
    attendance: "उपस्थिति",
    reports: "रिपोर्ट",
    members: "सदस्य",
    profile: "प्रोफ़ाइल",
    logout: "लॉगआउट",
    apply_filter: "फ़िल्टर लागू करें",
    reset: "रीसेट",
    group: "समूह",
    status: "स्थिति",
    member: "सदस्य",
    from_date: "शुरुआत की तारीख",
    to_date: "अंतिम तारीख",
    all_status: "सभी स्थिति",
    all_members: "सभी सदस्य",
    all_groups: "सभी समूह",
    present: "उपस्थित",
    pv_vardi: "पीवी (वर्दी)",
    absent: "अनुपस्थित",
    loading: "लोड हो रहा है...",
    no_records: "इस फ़िल्टर के लिए कोई रिकॉर्ड नहीं",
    pending: "लंबित",
    approved: "स्वीकृत",
    all: "सभी",
    welcome: "आपका स्वागत है",
    admin_panel: "व्यवस्थापक पैनल",
    member_portal: "सदस्य पोर्टल",
    mark_attendance: "उपस्थिति दर्ज करें",
    my_records: "मेरे रिकॉर्ड",
    activity: "गतिविधि",
    change_password: "पासवर्ड बदलें",
    settings: "सेटिंग्स",
    group_duty: "समूह {group} ड्यूटी",
    quick_actions: "त्वरित कार्रवाई",
    attendance_pv_only: "उपस्थिति % (केवल पीवी)",
    present_p: "उपस्थित (P)",
    absent_a: "अनुपस्थित",
    my_duty_this_month: "इस महीने मेरी ड्यूटी",
    fixed_pattern: "{month} — निश्चित पैटर्न, वास्तविक तिथियां नीचे हैं",
    no_sewa_assigned: "कोई सेवा आवंटित नहीं की गई",
    admin_will_set: "व्यवस्थापक आपके लिए पहली, दूसरी, तीसरी या अतिरिक्त सेवा निर्धारित करेगा।",
    this_months_attendance: "इस महीने की उपस्थिति",
    not_counted_in_percent: "% में नहीं गिना गया",
    pv_counts_toward: "4 पीवी = 100% · % की ओर गियता है",
    sewa_pattern_set: "सेवा पैटर्न सेट है — इस महीने की तारीखों की गणना नहीं की जा सकी।",
    sign_out: "साइन आउट",
    no_approved_records: "इस महीने कोई स्वीकृत रिकॉर्ड नहीं है",
    mark_attendance_at_centre: "किसी स्वीकृत केंद्र पर उपस्थिति दर्ज करें।",
    admin_dashboard: "Admin Dashboard",
    member_dashboard: "Dashboard",
    broadcast_notice: "Broadcast Notice",
    send_new_notice: "Send New Notice",
    notice_title: "Notice Title",
    message: "Message",
    notice_type: "Notice Type",
    information_blue: "Information (Blue)",
    important_warning_orange: "Important/Warning (Orange)",
    announcement_green: "Announcement (Green)",
    send_broadcast: "Send Broadcast",
    recent_notices: "Recent Notices",
    no_active_notices: "No active notices sent yet.",
    delete_broadcast: "Delete Broadcast",
    delete_broadcast_confirm: "Are you sure you want to delete the broadcast \"{title}\"? This action cannot be undone.",
    analytics: "Analytics",
    total_members: "Total Members",
    monthly_attendance: "Monthly Attendance",
    pending_approvals: "Pending Approvals",
    todays_status: "Today's Status",
    attendance_trend: "Attendance Trend (Last 6 Months)",
    group_wise_attendance: "Group-wise Attendance",
    top_performers: "Top Performers (This Month)",
    rank: "Rank",
    name: "Name",
    area: "Area",
    approval: "Approval",
    approved_by: "Approved By",
    records: "records",
    my_profile: "My Profile",
    edit_your_profile: "Edit your profile",
    mobile_number: "Mobile Number",
    save_changes: "Save changes",
    download_excel: "Download Excel",
    download_pdf: "Download PDF",
    download_csv: "Download CSV",
    mark_attendance_quick: "Mark Attendance",
    my_duty: "My Duty",
    duty_schedule: "Duty Schedule",
    select_location: "Select Location",
    capture_selfie: "Capture Selfie",
    submit_attendance: "Submit Attendance",
    app_settings: "App Settings",
    notifications: "Notifications",
    sort: "Sort",
    loading_please_wait: "Loading, please wait...",
    no_data_available: "No data available",
    coming_soon: "Coming Soon",
    recent_attendance: "हाल की उपस्थिति",
  },
  mr: {
    dashboard: "डॅशबोर्ड",
    attendance: "उपस्थिती",
    reports: "अहवाल",
    members: "सदस्य",
    profile: "प्रोफाइल",
    logout: "लॉगआउट",
    apply_filter: "फिल्टर लागू करा",
    reset: "रीसेट",
    group: "गट",
    status: "स्थिती",
    member: "सदस्य",
    from_date: "सुरुवात तारीख",
    to_date: "शेवटची तारीख",
    all_status: "सर्व स्थिती",
    all_members: "सर्व सदस्य",
    all_groups: "सर्व गट",
    present: "हजर",
    pv_vardi: "पीव्ही (वर्दी)",
    absent: "गैरहजर",
    loading: "लोड होत आहे...",
    no_records: "या फिल्टरसाठी कोणतेही रेकॉर्ड नाहीत",
    pending: "प्रलंबित",
    approved: "मंजूर",
    all: "सर्व",
    welcome: "स्वागत आहे",
    admin_panel: "प्रशासक पॅनेल",
    member_portal: "सदस्य पोर्टल",
    mark_attendance: "हजेरी लावा",
    my_records: "माझे रेकॉर्ड",
    activity: "हालचाल",
    change_password: "पासवर्ड बदला",
    settings: "सेटिंग्ज",
    group_duty: "गट {group} ड्यूटी",
    quick_actions: "त्वरित कृती",
    attendance_pv_only: "उपस्थिती % (केवळ पीव्ही)",
    present_p: "हजर (P)",
    absent_a: "गैरहजर",
    my_duty_this_month: "या महिन्यात माझी ड्यूटी",
    fixed_pattern: "{month} — निश्चित नमुना, वास्तविक तारखा खाली आहेत",
    no_sewa_assigned: "कोणतीही सेवा नियुक्त केलेली नाही",
    admin_will_set: "प्रशासक तुमच्यासाठी पहिली, दुसरी, तिसरी किंवा अतिरिक्त सेवा निर्धारित करेल।",
    this_months_attendance: "या महिन्याची उपस्थिती",
    not_counted_in_percent: "% मध्ये मोजले जात नाही",
    pv_counts_toward: "4 पीव्ही = 100% · % मध्ये मोजले जाते",
    sewa_pattern_set: "सेवा नमुना सेट केला आहे — या महिन्याच्या तारखांची गणना करता आली नाही।",
    sign_out: "साइन आउट",
    no_approved_records: "या महिन्यात कोणतेही मंजूर रेकॉर्ड नाहीत",
    mark_attendance_at_centre: "मंजूर केंद्रावर हजेरी लावा।",
    recent_attendance: "अलीकडील उपस्थिती",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");

  useEffect(() => {
    const saved = localStorage.getItem("app_lang") as Language;
    if (saved && (saved === "en" || saved === "hi" || saved === "mr")) {
      setLanguageState(saved);
      // Update HTML lang attribute on initial load
      if (typeof document !== "undefined") {
        document.documentElement.lang = saved;
      }
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("app_lang", lang);
    // Update HTML lang attribute for accessibility and SEO
    if (typeof document !== "undefined") {
      document.documentElement.lang = lang;
    }
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
