import { NextResponse } from "next/server";
import { prisma } from "@/lib/db";

const userGroups: Record<string, string> = {
  'Ashok Srinath Prajapati': '1',
  'Manoj Satyanarayan Vishwakarma': '4&5',
  'Arun Janu Bhanat': '3',
  'Sandeep Mansing Mane': '2',
  'Shashikant Guptanath Maurya': '4&6',
  'Radheshyam Shivgen Vishwakarma': '1',
  'Anand Baburao More': '8',
  'Rajesh Srinath Prajapati': '2',
  'Sunil Sakharam Deve': '4',
  'Ramesh Gopal Bhadirke': '7',
  'Ramesh Dhondu Baikar': '5',
  'Sitaram Sakharam Deve': '7',
  'Sandesh Jayram Mandavkar': '2',
  'Ravindra Mansingh Janala': '5',
  'Vinod Kumar Ramvilas Gupta': '7',
  'Kulbahadur Rewansingh Aale': '1',
  'Sanjay Sahdev Mandvkar': '8',
  'Sitaram Ganpat Joshi': '6',
  'Babu Sakharam Jadhav': '4',
  'Ramasare Surajbali Vishwakarma': '3',
  'Jayesh Mathurdas Chandarana': '6',
  'Kishan Narayan Kovoor': '8',
  'Anil Naresh Patil': '3',
  'Pankaj Padmakar Arekar': '6',
  'Sureshchandra Ghurahu Vishwakarma': '3',
  'Subhash Soma Nawale': '3',
  'Radheshyam Ramafer Vishwakarma': '5',
  'Rupesh Namdeo Patil': '5',
  'Jagdish Ghurahoo Vishwakarma': '7',
  'Gajanan Namdeo Raut': '6',
  'Ram Babaji Ghurup': '5',
  'Vishal Vitthal Gosavi': '2',
  'Ganpat Sakharam Nawale': '6',
  'Rakesh Fulchand Sahani': '3',
  'Munibchand Pannalal Vishwakarma': '3',
  'Sudhir Yashwant Bargode': '4',
  'Umesh Pravinbhai Nanda': '8',
  'Subhash Vishwanath Sahani': '1',
  'Pyarelal Chhabburam Prajapati': '3',
  'Amarjeet Rameshwar Gupta': '8',
  'Shivbachan Ramruchi Prajapati': '8',
  'Ravindra Chandrakant Jambhale': '6',
  'Sudama Kumbhakarn Rajbhar': '8',
  'Subhash Bhagoji Dhanawade': '5',
  'Prabhudeo Rajendra Gupta': '7',
  'Ganesh Namdev Patil': '6',
  'Subhash Pandurang Ghadigaonkar': '6',
  'Dashrath Shivaji Nikam': '1',
  'Dilip Shankar Ranjane': '5',
  'Mukund Laxman Mengde': '5',
  'Ramkirat Manai Prajapati': '7',
  'Brijkishor Rampati Kushwaha': '8',
  'Lalbahadur Vishwakarma': '3',
  'Santlal Fekuram Chaurasia': '7',
  'Sitaram Rajaram Rohidas': '5',
  'Phoolchand Vishwanath Pal': '4',
  'Anil Shambhu Kotavdekar': '2',
  'Anil Kumar Kedarnath Prajapati': '8',
  'Sunil Shambhu Kotawdekar': '4',
  'Ravindra Mewalal Vishwakarma': '8',
  'Ghanshyam Sukhai Prajapati': '2',
  'Rajesh Ramprasad Vishwakarma': '7',
  'Srikant Shivaji Nikam': '1',
  'Narendra Janu Bhanat': '4',
  'Shrikant Guptanath Maurya': '5',
  'Manoj Naresh Patil': '2',
  'Deepak Chandrakant Kadu': '5',
  'Dipak Arjun Shivgan': '8',
  'Mahesh Laxman More': '8',
  'Mitesh Harishchandra Mulam': '1',
  'Manoj Gulabrao Sankapal': '4',
  'Nitin Gajanan Sayakar': '5',
  'Mahendra Chandrakant Jamble': '2',
  'Hardev Sukthi Yadav': '4',
  'Nilesh Gajanan Saykar': '5',
  'Rupesh Dipak Gujar': '7',
  'Mantrilal Pannalal Vishwakarma': '7',
  'Vivek Indrapal Saroj': '2',
  'Mangesh Laxman More': '6',
  'Ajay Dalajeet Vishwakarma': '3',
  'Arun Kumar Mahendra Vishwakarma': '7',
  'Mandar Mukund Mengade': '8',
  'Sandeep Arvind Maurya': '2',
  'Anil Phoolchand Pal': '1',
  'Chetan Keshav Kotavdekar': '7',
  'Shiv Kumar Bansraj Yadav': '5',
  'Ramchandar Shyamlal Nishad': '7',
  'Ramavadh Rambachan Yadav': '8',
  'Parshuram Shivmurat Vishwakarma': '8',
  'Shailesh Harishchandra Mulam': '1',
  'Satish Changdev Kudekar': '3',
  'Satyendraprasad Rampratap Vishwakarma': '4',
  'Pralhad Arjun Shivgan': '7',
  'Rishikant Guptnath Maurya': '6',
  'Dayaram Ramdas Saroj': '4',
  'Shivsagar Dinanath Yadav': '1',
  'Avadhraj Parmeshwar Sahani': '4',
  'Vishwas Keshav Kotavdekar': '8',
  'Satyaprakash Jogbahadur Kesi': '4',
  'Kiran Sunil Deve': '2',
  'Vishwanath Maruti Shigvan': '2',
  'Anand Kedarnath Prajapati': '4',
  'Suraj Dattaram Beloshe': '8',
  'Dhiraj Prakash Triloker': '5',
  'Mayur Ramesh Lataye': '5',
  'Rajesh Phoolchand Sahani': '3',
  'Brahmadev Dayashanker Sahani': '4',
  'Baijnath Dayashanker Sahani': '1',
  'Kishor Kumar Raghurai Benbanshi': '7',
  'Satyanarayan Bekelal Prajapati': '3',
  'Ramgopal Maataprasad Chauhan': '7',
  'Shivshankar Ramasare Vishwakarma': '8',
  'Kaushal Sandesh Mandavkar': '6',
  'Makardhwaj Shriramnarayan Thakur': '7',
  'Sumit Kumar Kishor Benbanshi': '7',
  'Ravindra Ratnaker Kocharekar': '6',
  'Vinayak Ramesh Latye': '1',
  'Manish Rajesh Prajapati': '2',
  'Prashant Dilip Bhojane': '4',
  'Vikas Munibchand Vishwakarma': '7',
  'Aadesh Tukaram Kamble': '1',
  'Sakharam Tukaram Devare': '5',
  'Shubham Rajkishor Vishwakarma': '1',
  'Kshitij Rajesh Vishwakarma': '7',
  'Vishnu Firatoo Rajbhar': '4',
  'Shubham Shivaji Patil': '5',
  'Dipesh Dilip Bhojane': '3',
  'Rajan Firatu Rajbhar': '1',
  'Vivek Mukund Deve': '5',
  'Roshan Sitaram Joshi': '2',
  'Sumeet Shivkumar Yadav': '6',
  'Anurag Arvind Singh': '6',
  'Suvitkumar Sureshchandra Vishwakarma': '3',
  'Sujal Vithal Shelar': '6',
  'Roshan Ramchandra Jadhav': '6',
  'Sundaram Rajesh Vishwakarma': '6',
  'Amar Hari Mahadik': '6',
  'Prashant Bhimrao Patil': '6',
  'Praveen Kumar Ramnihore Pal': '4',
  'Aakash Tukaram Kamble': '1',
  'Harsh Bhavesh Shirke': '1',
  'Pratham Ravindra Janala': '5',
  'Suyash Anand More': '1',
  'Surendra Subhash Sahani': '2',
  'Pratham Rajkishor Vishwakarma': '3',
  'Mukesh Subhash Dhanawade': '3',
  'Manmohan Radheshyam Vishwakarma': '3',
  'Vinay Ravindra Janala': '8',
  'Mandhir Radheshyam Vishwakarma': '3',
  'Aditya Ghanshyam Prajapati': '3',
  'Deepak Chhedi Jaiswar': '7',
  'Hardik Shivadhaar Yadav': '6',
  'Vinit Ramsakal Prajapati': '2',
  'Jitesh Rajesh Ram': '2',
  'Sanskar Sagar Patil': '6',
  'Prem Avadhraj Sahani': '1',
  'Gyaanchand Motilal Vishwakarma': '1',
  'Arvind Ramraj Maurya': '4',
  'Kiran Dattaram Beloshe': '5',
  'Syambali Ramlakhan Vishwakarma': '2',
  'Harsh Manoj Sankapal': '4',
  'Dashrath Bhikhu Dhangat': '6',
  'Suchitra Sandesh Mandavkar': '1',
  'Jyoti Kishor Wagh': '2',
  'Ujjwala Maruti Shigvan': '6',
  'Minakshi Kishor Bandagale': '4',
  'Sonali Subhash Dhanawade': '5',
  'Geeta Premanand Jadhav': '5',
  'Vaishali Madhukar Gudekar': '5',
  'Vandana Anil Patil': '3',
  'Manisha Rupesh Patil': '6',
  'Archana Umesh Maurya': '5',
  'Sunita Arun Bhanat': '3',
  'Jyoti Subhash Batawale': '5',
  'Ranjana Ganpat Nawale': '5',
  'Bharati Ramesh Late': '3',
  'Shaila Prakash Tandelkar': '5',
  'Jyoti Nilesh Vishwakarma': '3',
  'Nandini Maruti Shigvan': '6',
  'Dipali Sandeep Kadam': '2',
  'Nilam Premchand Gupta': '2',
  'Sushila Raju Vishwakarma': '3',
  'Suvarna Gajanan Raut': '8',
  'Sujata Sitaram Deve': '7',
  'Dipti Dipak Kadu': '5',
  'Sanjana Prakash Gaikwad': '1',
  'Sonal Sunil Deve': '6',
  'Punam Mitesh Mulam': '7',
  'Surekha Sakharam Dhangat': '5',
  'Shraddha Shashikant Maurya': '6',
  'Pavitra Jogbahadur Kesi': '2',
  'Rasika Dilip Ranjane': '5',
  'Madhavi Mahadev Jambhale': '5',
  'Sushma Ajit Parave': '5',
  'Sarita Rajesh Sahani': '1',
  'Madhu lata Munibchand Vishwakarma': '1',
  'Pramila Virendra Vishwakarma': '2',
  'Geeta Ravindra Janala': '6',
  'Suganti Ram Kailash Shah': '7',
  'Vidanti Ram Kailash Shah': '7',
  'Usha Ramayan Vishwakarma': '7',
  'Kalavati Ashok Prajapati': '7',
  'Barkha Dalajeet Vishwakarma': '3',
  'Mamta Sanjay Upadhyay': '6',
  'Swati Sitaram Joshi': '8',
  'Sneha Sitaram Joshi': '6',
  'Snehal Sunil Deve': '6',
  'Priyanka Raghu Nath Salvi': '8',
  'Manali Mukund Deve': '6',
  'Shweta Sitaram Kudkar': '2',
  'Deepika Dilip Bhojane': '2',
  'Urmila Subhash Sahani': '2',
  'Geeta Rajkishor Vishwakarma': '8',
  'Manda Krushna Patil': '1',
  'Bandini Vilas Balkate': '4',
  'Reena Dashrath Nikam': '4',
  'Aakansha Subhash Dhanawade': '8',
  'Anita Kishor Benbanshi': '2',
  'Sunita Subhash Sahani': '2',
  'Roshni Eknath Tambe': '8',
  'Shalini Sureshchandra Vishwakarma': '5',
  'Sushmita Shyambihari Morya': '4',
  'Pooja Santosh Vishwakarma': '4',
  'Sarita Rajesh Prajapati': '8',
  'Anjali Indrapal Bagdi': '5',
  'Pooja Subhash Sahani': '4',
  'Sonam Rajkishor Vishwakarma': '7',
  'Esha Umesh Maurya': '7',
  'Kajal Shivaji Patil': '8',
  'Pavitra Kulbahadur Ale': '8',
  'Suchita Sureshchandra Vishwakarma': '3',
  'Simran Sandesh Mandavkar': '8',
  'Milan Dilip Bhojane': '4',
  'Asha Baburao Jadhav': '4',
  'Jayashree Shantaram Raynak': '7',
  'Malati Radhyeshyam Vishwakarma': '4',
  'Anuradha Mukund Mengade': '5',
  'Nalini Raghunath Salavi': '3',
  'Rasika Ratnaker Kocharekar': '4',
  'Kishori Munibchand Vishwakarma': '1',
  'Pramila Satyanarayan Prajapati': '2',
  'Shakuntala Anand More': '2',
  'Subhangi Keshav Kotavdekar': '4',
  'Sapna Sunil Deve': '6',
  'Miradevi Shriramnarayan Thakur': '3',
  'Pratibha Prakash Tirlotkar': '3',
  'Geeta Kishor Benbanshi': '2',
  'Minal Mukund Deve': '6',
  'Pranali Sitaram Joshi': '6',
  'Namita Sakharam Devare': '8',
  'Ishika Arun Bhanat': '3',
  'Jyoti Satyanarayan Prajapati': '4',
  'Premlata Mantrilal Vishwakarma': '1',
  'Sujata Santosh Patil': '1',
  'Supriya Dipak Shivgan': '1',
  'Ranju Rishikant Maurya': '6',
  'Manju Devi (Shashilata) Shivsagar Yadav': '4',
  'Chhaya Gavade (Sakshi Santosh Pawar)': '1',
  'Shalini Shyambihari Maurya': '8',
  'Roshni Pramod Vishwakarma': '1',
  'Anchal Amarjeet Gupta': '8',
  'Taruna Rajesh Bhatt': '7',
  'Urmila Rammilan Prajapati': '3',
  'Vibha Kamlesh Vishwakarma': '4',
  'Utkarsh Santosh Pawar': '4',
  'Priya Vitthal Tungatkar': '2',
  'Ankita Shastrilal Vishwakarma': '7',
  'Sujata Subhash Ghadigaonkar': '3',
  'Sujata Siddhesh Patil': '1',
  'Sakshi Santosh Pawar': '1',
  'Shashilata Shivsagar Yadav': '1',
  'Shivkumari Hardev Yadav': '1',
  'Pramila Tribuvan Kashyap': '3',
  'Asha Shivkumar Yadav': '5',
  'Anita Rajesh Bhatt': '7',
  'Sarita Baliram Pawar': '8',
  'Rekha Samsher Janala': '6',
  'Sonali Rajesh Vishwakarma': '4',
  'Vrunmaye Sanjay Shinde': '5',
  'Anita Shrikant Maurya': '6',
  'Abhay Shrikant Maurya': 'N1',
  'Prajwal Sagar Patil': 'N2',
  'Hardik Shivkumar Yadav': 'N3',
  'Satyam Sushil Yadav': 'N4',
  'Vedant Kishor Nikam': 'N5',
  'Tejas Rajendra Dalvi': 'N6',
  'Lucky Ramaasare Prajapati': 'N7',
  'Lakshya Anil Kotavdekar': 'N8',
  'Shivam Arvind Sharma': 'N9',
  'Mohit Rambrij Chauhan': 'N10',
  'Bhaskar Bramhadev Sahani': 'N11',
  'Nayan Rakesh Sahani': 'N12',
  'Aayush Sanjay Maurya': 'N13',
  'Sandesh Ramjiyavan Verma': 'N14',
  'Aayush Sandeep Kadam': 'N15',
  'Aaradhy Vaishali Tambe': 'N16',
  'Aayush Ramavadh Yadav': 'N17',
  'Sandeep Sanjay Shinde': 'N18',
  'Naman Anand Verma': 'N19',
  'Shukran Manoj Vishwakarma': 'N20',
  'Alisha Shrikant Maurya': 'N1',
  'Tanishka Vijay Bhosale': 'N2',
  'Sharayu Sandesh Namugade': 'N3',
  'Shravani Vithal Shelar': 'N4',
  'Simran Vijay Dakwa': 'N5',
  'Sunakshi Pradeep Vishwakarma': 'N6',
  'Ishwari Mahadev Jadhav': 'N7',
  'Aditi Anil Gupta': 'N8',
  'Mayuri Mahadev Jadhav': 'N9',
  'Akshta Datta Kurne': 'N10',
  'Anita Datta Kurne': 'N11',
  'Shalini Mansingh Patel': 'N12'
};

export async function POST(request: Request) {
  try {
    const results = [];
    
    for (const [name, groupStr] of Object.entries(userGroups)) {
      let groups: number[] = [];
      if (!groupStr.startsWith('N')) {
        groups = groupStr.split('&').map(Number).filter(n => !isNaN(n));
      }
      
      const user = await prisma.user.findFirst({
        where: { name: { equals: name, mode: 'insensitive' } }
      });
      
      if (user) {
        await prisma.user.update({
          where: { id: user.id },
          data: { groups }
        });
        results.push({ name, status: 'Updated', groups });
        console.log(`Updated user: ${name} to groups: [${groups}]`);
      } else {
        results.push({ name, status: 'User not found' });
        console.log(`User not found: ${name}`);
      }
    }
    
    return NextResponse.json({ 
      success: true, 
      message: 'Group update complete', 
      results 
    });
  } catch (error) {
    console.error('Error updating groups:', error);
    return NextResponse.json(
      { success: false, message: 'Error updating groups', error: String(error) },
      { status: 500 }
    );
  }
}
